### ISSUE TITLE
Logex and Fastmerge bugs

### ISSUE THREAD

**Issue by c-zhou** [thegenemyers/FASTK#13]
Hello Gene,

Logex and Fastmerge assume the `ibyte` field is always 3.  I ran into a very small genome (~40 Mb), which gave me 2. The histograms from Logex and Fastmerge are correct. The Kmer tables, however, are junks.

(1) Line 1026 and 1044 should be something like `bst+ibyte` here instead of `bst+3`?
https://github.com/thegenemyers/FASTK/blob/d69435929733dddb600b019fde1ab7f438c05e3c/Logex.c#L1026
https://github.com/thegenemyers/FASTK/blob/d69435929733dddb600b019fde1ab7f438c05e3c/Logex.c#L1044

(2) Line L1028 and L1050 should be something like this?
<pre>
x = 0;
if (ibyte==3)
    x = ((int) bst[0] << 16) | (bst[1] << 8) | bst[2];
else if(ibyte==2)
    x = ((int) bst[0] << 8) | bst[2];
else if(ibyte==1)
    x = bst[0];
</pre>
https://github.com/thegenemyers/FASTK/blob/d69435929733dddb600b019fde1ab7f438c05e3c/Logex.c#L1028
https://github.com/thegenemyers/FASTK/blob/d69435929733dddb600b019fde1ab7f438c05e3c/Logex.c#L1050

(3) You write the `minval` as 1. Do you think if it is worth updating it after Logex?
https://github.com/thegenemyers/FASTK/blob/d69435929733dddb600b019fde1ab7f438c05e3c/Logex.c#L1391

(4) another minor point is do you think if it makes sense to grant the group read permission to files generated by Logex?

Fastmerge is pretty much the same as Logex.

Best,
Chenxi

**Comment by thegenemyers** [comment]
Hi Chenxi,

    I'm very impressed at how quickly you understand my code albeit your 
understanding is not completely
correct.

    First, Fastmerge is not yet complete and is under development, so 
please ignore it for now.  Note that
it is not yet documented in the README.  Apologies.

    The value of ibyte, the prefix table width, depends on k and the 
size of the table (see FastK/count.c lines 1614-1619).
For K = 31 or 21, ibyte will be 3 if the table has more than 256K 
entries, 2 if it has more than 1024, and 1 otherwise.
All the table *input* is through the library, libfastk.c, which handles 
the prefix correctly so that if input tables have different
prefix widths it should all be fine.  Only for the table *output* do I 
fix at 3 and this should cause a problem only if K < 12.
I was lazy and should probably arrange it so that Logex works for K < 
12, but it doesn't seem this is true of any of your
test case, so for the suggestions you give: did they really fix 
problem?  I just did a run with k=21 a few days ago and Logex was fine
with the new patch of 4 days ago.  Please advise.

    In thinking about your comments and reviewing the code, I did spot 
something that could cause a problem when the
input tables have different prefix widths, namely the division of the 
tables into parts for threads around line 1344.
I will fix this but the circumstances should be very rare.

    If you could send me inputs that give incorrect results that would 
be great.  Its critical Logex be correct as much of
my Merqury.FK implementation depends on it.

    Thanks so much,  Gene

**Comment by c-zhou** [comment]
Hi Gene,

I sent you an email with the genome assembly which produces 'ibyte=2'.

Thanks very much for your detailed explaination about how 'ibyte' was determined. I think the problem with the data I have is it contains only 33M mers and FastK requires at least 64M mers (instead of 256K - am I right? FastK/count.c lines 1614-1619) to have 'ibyte=3'.

Best,
Chenxi

**Comment by c-zhou** [comment]
problem solved
